# Index notation and `einsum`


The key concept with index notation is that _tensor_ quantities
can be described by a number of components. These components can
be labelled by an index (subindex or superindex) which indicates
the number and form of the components. Thus, instead of writing
the set of components $(x_1, x_2, x_3)$, we can write $x_i$—assuming
that it is clear that $i=1, 2, 3$, as it is in $\mathbb{R}^3$.

We could have more complicated quantities, such as second order
or higher order tensors. For example $\sigma_{ij}$ represent
the 9 components of the stress tensor.


## Summation convention

Consider the expression

$$x_1 y_1 + x_2 y_2 x_3 y_3\, ,$$

which can be interpreted as the scalar product of
vectors $\mathbf{x} = (x_1, x_2, x_3)$ and
$\mathbf{y} = (y_1, y_2, y_3)$ in $\mathbb{R}^3$.
This expression can be written as

$$\sum_{i=1}^3 x_i y_i\, .$$

It is pretty common to have repeated indices when
summation happens. The convention is to avoid the
summation symbol when an index is repeated twice
(and only twice).

Using this convention the scalar product of
the vectors $x_i$ and $y_i$ is written as

$$x_i y_i\, .$$

The repeated index is called a _dummy_ index as opposed to one that is not summed,
which is referred to as a _free_ index. Since a dummy index indicates a summation
operation, any index can be used without changing the result. For example,
$x_i$ $y_i$ and $x_j$ $y_j$ are the same product.


When there are more than two summation operations to be performed caution
must be exercised in the use of the summation convention. The following rules can
therefore help

- If a subscript occurs twice in a term in an equation, then it must be summed
over its range. These are the repeated or dummy indices, e.g.,

$$C_{ikk} = C_{i11} + C_{i22} + C_{i33}$$

- If a subscript occurs once in a term then it must occur once in every other term
  in the equation. These are the _free_ indices, e.g.,

\begin{align}
& &F_1 = ma_1\\
&F_i = ma_i \Rightarrow &F 2 = ma_2\\
& &F_3 = ma_3
\end{align}

- If a subscript occurs more than twice in a term, then it is a mistake , e.g.,

$$A_{iij} B_{ij}$$

In [1]:
import numpy as np

### Inner product of vectors

In [2]:
x = np.array([1, 2, 3])
y = np.array([0, 2, 5])

In [3]:
%%timeit
np.einsum('i,i', x, y)

5.8 µs ± 52.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [4]:
%%timeit
x.dot(y)

1.11 µs ± 105 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [5]:
%%timeit
aux = 0
for xi, yi in zip(x, y):
    aux += xi * yi

2.74 µs ± 111 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
%%timeit
x.T @ y

2.79 µs ± 98.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### Matrix-vector product

In [7]:
A = np.random.rand(2, 2)
b = np.random.rand(2)

In [8]:
A @ b

array([0.50009434, 0.95953381])

In [9]:
np.einsum('ij,j', A, b)

array([0.50009434, 0.95953381])

In [10]:
A.dot(b)

array([0.50009434, 0.95953381])

In [11]:
%%timeit
A @ b

2.9 µs ± 44 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
%%timeit
np.einsum('ij,j', A, b)

6.88 µs ± 14.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
%%timeit
A.dot(b)

823 ns ± 13 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Matrix-matrix product

In [14]:
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)

In [15]:
np.einsum('ij,jk->ik', A, B)

array([[0.94374907, 0.989794  , 1.25289813, 1.72656549, 1.25021439],
       [0.65019672, 1.10339941, 1.31472525, 1.66957923, 1.18893891],
       [0.89776685, 1.09145296, 1.0547807 , 1.63685222, 0.91698122],
       [0.82475805, 0.78387961, 1.44660302, 1.73978562, 1.2316314 ],
       [1.04440475, 1.04789787, 1.74847574, 2.21215723, 1.48516131]])

In [16]:
A @ B

array([[0.94374907, 0.989794  , 1.25289813, 1.72656549, 1.25021439],
       [0.65019672, 1.10339941, 1.31472525, 1.66957923, 1.18893891],
       [0.89776685, 1.09145296, 1.0547807 , 1.63685222, 0.91698122],
       [0.82475805, 0.78387961, 1.44660302, 1.73978562, 1.2316314 ],
       [1.04440475, 1.04789787, 1.74847574, 2.21215723, 1.48516131]])

In [17]:
C = np.zeros_like(A)
for i in range(5):
    for j in range(5):
        for k in range(5):
            C[i, k] += A[i, j] * B[j, k]
C

array([[0.94374907, 0.989794  , 1.25289813, 1.72656549, 1.25021439],
       [0.65019672, 1.10339941, 1.31472525, 1.66957923, 1.18893891],
       [0.89776685, 1.09145296, 1.0547807 , 1.63685222, 0.91698122],
       [0.82475805, 0.78387961, 1.44660302, 1.73978562, 1.2316314 ],
       [1.04440475, 1.04789787, 1.74847574, 2.21215723, 1.48516131]])

In [18]:
%%timeit
np.einsum('ij,jk->ik', A, B)

7.75 µs ± 132 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [19]:
%%timeit
A @ B

4.05 µs ± 58.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
%%timeit
C = np.zeros_like(A)
for i in range(5):
    for j in range(5):
        for k in range(5):
            C[i, k] += A[i, j] * B[j, k]

177 µs ± 1.23 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### Triads

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

In [22]:
np.einsum('i,j->ij', a, b)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [23]:
np.outer(a, b)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [24]:
a[:, None] * b

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [25]:
%%timeit
np.einsum('i,j->ij', a, b)

7.18 µs ± 28.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [26]:
%%timeit
np.outer(a, b)

8.66 µs ± 669 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [27]:
%%timeit
a[:, None] * b

4.15 µs ± 62.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
np.einsum('i,j,k->ijk', a, b, c)

array([[[ 28,  32,  36],
        [ 35,  40,  45],
        [ 42,  48,  54]],

       [[ 56,  64,  72],
        [ 70,  80,  90],
        [ 84,  96, 108]],

       [[ 84,  96, 108],
        [105, 120, 135],
        [126, 144, 162]]])

In [29]:
(a[:, None] * b)[:, :, None] * c

array([[[ 28,  32,  36],
        [ 35,  40,  45],
        [ 42,  48,  54]],

       [[ 56,  64,  72],
        [ 70,  80,  90],
        [ 84,  96, 108]],

       [[ 84,  96, 108],
        [105, 120, 135],
        [126, 144, 162]]])

In [30]:
%%timeit
np.einsum('i,j,k->ijk', a, b, c)

9.12 µs ± 103 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [31]:
%%timeit
(a[:, None] * b)[:, :, None] * c

8.75 µs ± 34.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## References

1. The NumPy community (2021). numpy.einsum — NumPy v1.21 Manual. https://numpy.org/doc/stable/reference/generated/numpy.einsum.html. 
Accessed July 2021.

2. Alex Riley (2015). A Basic Introduction to NumPy's einsum – Ajcr – Haphazard Investigations. https://ajcr.net/Basic-guide-to-einsum/. Accessed July 2021.

In [33]:
# Execute this cell to load the notebook's style sheet, then ignore it
from IPython.core.display import HTML
css_file = 'custom.css'
HTML(open(css_file, "r").read())