## Example

Example 4.1 from


The Boundary Element Method for Engineers and Scientists



In [1]:
%matplotlib notebook

In [2]:
import numpy as np
from numpy.linalg import solve
import matplotlib.pyplot as plt
import meshio
from bem import (assem, eval_sol, read_geo_gmsh,
                 rearrange_mats, rearrange_sol,
                 surf_plot, create_rhs)

In [5]:
mesh, coords, elems, x_m, y_m, id_dir, id_neu = read_geo_gmsh("files/disk.msh", [0, 1], [2, 3])

In [13]:
# Nodes
coords = np.array([
    [0.00, 0.00],
    [0.25, 0.00],
    [0.50, 0.00],
    [0.75, 0.00],
    [1.00, 0.00],
    [1.00, 0.25],
    [1.00, 0.50],
    [1.00, 0.75],
    [1.00, 1.00],
    [0.75, 1.00],
    [0.50, 1.00],
    [0.25, 1.00],
    [0.00, 1.00],
    [0.00, 0.75],
    [0.00, 0.50],
    [0.00, 0.25]])
x_m = np

In [14]:
# Elements
elems = np.zeros((16, 2), dtype=int)
elems[:, 0] = range(0, 16)
elems[:, 1] = list(range(1, 16)) + [0]

In [19]:
Gmat, Fmat = assem(coords, elems)

In [21]:
id_dir, id_neu

In [32]:
id_dir = [4, 5, 6, 7, 12, 13, 14, 15]
id_neu = [0, 1, 2, 3, 8, 9, 10, 11]
A, B = rearrange_mats(Fmat, Gmat, id_dir, id_neu)

In [41]:
# x_m, y_m = 0.5*(coords[elems[:, 0]] + coords[elems[:, 1]]).T
# u_bc = [200] * 4 + [100] * 4
# q_bc = [0] * 8
# rhs = create_rhs(x_m, y_m, u_bc, q_bc, id_dir, id_neu)
rhs = np.array([0, 0, 0, 0,
                200, 200, 200, 200,
                0, 0, 0, 0,
                100, 100, 100, 100])

In [42]:
sol = solve(A, B.dot(rhs))
#u_bound, q_bound = rearrange_sol(sol, rhs, id_dir, id_neu)

In [43]:
sol

array([ 102.73822948,  105.60249143,  140.35984675,  223.57053194,
        100.91252995, -306.11302017, -306.11302017,  100.91252995,
        223.57053194,  140.35984675,  105.60249143,  102.73822948,
        253.13968651,  -12.04197207,  -12.04197207,  253.13968651])

In [35]:
#solution = eval_sol(mesh.points[:, :2], coords, elems, u_bound, q_bound)

In [36]:
# ax = surf_plot(mesh, 4, solution)
# ax.set_xticks([])
# ax.set_yticks([])
# ax.set_zticks([])

In [37]:
u_bound

array([102.73822948, 105.60249143, 140.35984675, 223.57053194,
       200.        , 200.        , 200.        , 200.        ,
       223.57053194, 140.35984675, 105.60249143, 102.73822948,
       100.        , 100.        , 100.        , 100.        ])

In [31]:
q_bound

array([ 100.91252995, -306.11302017, -306.11302017,  100.91252995,
          0.        ,    0.        ,    0.        ,    0.        ,
        253.13968651,  -12.04197207,  -12.04197207,  253.13968651,
          0.        ,    0.        ,    0.        ,    0.        ])